CREATE TABLE IF NOT EXISTS `page_views` (
  `id` varchar(255) PRIMARY KEY,
  `site_id` varchar(255),
  `session_id` varchar(255),
  `visitor_id` varchar(255),
  `path` varchar(255),
  `hostname` varchar(255),
  `title` varchar(255),
  `referrer` varchar(255),
  `referrer_source` varchar(255),
  `utm_source` varchar(255),
  `utm_medium` varchar(255),
  `utm_campaign` varchar(255),
  `utm_content` varchar(255),
  `utm_term` varchar(255),
  `country` varchar(255),
  `region` varchar(255),
  `city` varchar(255),
  `device_type` varchar(255),
  `browser` varchar(255),
  `browser_version` varchar(255),
  `os` varchar(255),
  `os_version` varchar(255),
  `screen_width` integer,
  `screen_height` integer,
  `is_unique` tinyint(1),
  `is_bounce` tinyint(1),
  `time_on_page` integer,
  `timestamp` varchar(255),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  SHARD KEY (`id`),
  SORT KEY (`site_id`, `timestamp`)
);
