CREATE TABLE IF NOT EXISTS "sessions" (
  "id" varchar(64) PRIMARY KEY,
  "site_id" varchar(64),
  "visitor_id" varchar(64),
  "entry_path" varchar(255),
  "exit_path" varchar(255),
  "referrer" varchar(255),
  "referrer_source" varchar(128),
  "utm_source" varchar(128),
  "utm_medium" varchar(64),
  "utm_campaign" varchar(128),
  "country" varchar(2),
  "region" varchar(64),
  "city" varchar(128),
  "device_type" varchar(16),
  "browser" varchar(32),
  "os" varchar(32),
  "page_view_count" integer,
  "event_count" integer,
  "is_bounce" boolean,
  "duration" integer,
  "started_at" varchar(32),
  "ended_at" varchar(32),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
