CREATE TABLE IF NOT EXISTS "page_views" (
  "id" varchar(64) PRIMARY KEY,
  "site_id" varchar(64),
  "session_id" varchar(64),
  "visitor_id" varchar(64),
  "path" varchar(255),
  "hostname" varchar(128),
  "title" varchar(255),
  "referrer" varchar(255),
  "referrer_source" varchar(128),
  "utm_source" varchar(255),
  "utm_medium" varchar(255),
  "utm_campaign" varchar(255),
  "utm_content" varchar(255),
  "utm_term" varchar(255),
  "country" varchar(2),
  "device_type" varchar(16),
  "browser" varchar(32),
  "browser_version" varchar(32),
  "os" varchar(32),
  "os_version" varchar(32),
  "screen_width" integer,
  "screen_height" integer,
  "is_unique" boolean,
  "is_bounce" boolean,
  "time_on_page" integer,
  "timestamp" varchar(32),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
