CREATE TABLE IF NOT EXISTS `sessions` (
  `id` varchar(255) PRIMARY KEY,
  `site_id` varchar(255),
  `visitor_id` varchar(255),
  `entry_path` varchar(255),
  `exit_path` varchar(255),
  `referrer` varchar(255),
  `referrer_source` varchar(255),
  `utm_source` varchar(255),
  `utm_medium` varchar(255),
  `utm_campaign` varchar(255),
  `country` varchar(255),
  `region` varchar(255),
  `city` varchar(255),
  `device_type` varchar(255),
  `browser` varchar(255),
  `os` varchar(255),
  `page_view_count` integer,
  `event_count` integer,
  `is_bounce` tinyint(1),
  `duration` integer,
  `started_at` varchar(255),
  `ended_at` varchar(255),
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  SHARD KEY (`id`),
  SORT KEY ()
);
